### ISSUE TITLE
Jenkins fails health checks too quickly

### ISSUE THREAD

**Issue by aaronwalker** [base2Services/ciinabox2#13]
If jenkins has already been running and you need to start it via the UI it can easily fail the health checks and the tasks get killed. 

It seems the default number of checks for unhealthy is 2 checks and for healthy is 5.

This should probably be the other way around as it want jenkins to be health in the ALB sooner and only fail if it's really not responding

**Comment by Guslington** [comment]
issue was with the upstream fargate component https://github.com/theonestack/hl-component-fargate-v2/releases/tag/0.7.2
